name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Package
        run: ./gradlew assemble

  test:
    runs-on: windows-latest
    needs: build
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: your_database
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U your_username"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -U your_username; do
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: jdbc:postgresql://localhost:5432/your_database
          DATABASE_USERNAME: your_username
          DATABASE_PASSWORD: your_password
        run: ./gradlew test
